dataset_root: "$@DATASET_ROOT if @DATASET_ROOT is not None else './data'"
data_module#train_dataset#data: "$monai.auto3dseg.datafold_read(f'@dataset_root/AMOS/amos22/dataset.json', basedir=f'@dataset_root/AMOS/amos22', key='training')[0]"